---
branches:
  only:
  - source
language: ruby
rvm:
- 1.9.3
before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
before_script:
  - export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
  - bundle exec rake setup_github_pages[$REPO_URL]
script:
  - bundle exec rake generate
after_script:
  - bundle exec rake deploy
env:
  # Generate OAuth tokens for travis-ci using bash:
  # $ gem install travis
  # $ curl -u 'tknerr' -d '{"scopes":["public_repo"], "note":"Travis access"}' https://api.github.com/authorizations
  # $ travis encrypt --add GH_TOKEN=your_token
  global:
    - GH_REPO="tknerr/tknerr.github.io"
    - secure: "sAMVfj8wzGmRNIGX2r2UyJyiGb44616kmrAvI05dL0eHK5BfkaK4uzoAniU0XUoHHWN8+MMRzEXQJPBYj3EIB/ZVkvWLe2mBU2hYJpeF7LxpfK/8L3OOt2Osbx09BYTiyg3PqSV/JerbV1XqQAiXPd+YhNzqDTLrqs+9/RiD0QA="
