---
branches:
  only:
  - source
language: ruby
rvm:
- 1.9.3
before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
before_script:
  - export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
  - bundle exec rake setup_github_pages[$REPO_URL]
script:
  - bundle exec rake generate
after_script:
  - bundle exec rake deploy
env:
  # Generate OAuth tokens for travis-ci using bash:
  # $ gem install travis
  # $ curl -u 'tknerr' -d '{"scopes":["public_repo"], "note":"Travis access"}' https://api.github.com/authorizations
  # $ travis encrypt --add GH_TOKEN=your_token
  global:
    - GH_REPO="tknerr/tknerr.github.io"
    - secure: "nO/o0wXelYaV/jeIoeFqmO5a2jvxtZK03e2aYyXsBVqJ7p8i6wSndBo3kbvFxnoLa+GA74gB27HlMxMaMJE7iFql/xCmk+sOiRhH0IFpahzHrZUTFjTJ20IV5CgQd+6AORXDKr/zM0OVHMf+IRO5JrmNorraV6vm+T76vRnsQyM="
